Capture test-runner-in-the-game output and forward it to UI
JetBrains/godot-support pull request #73
Opened 2022-01-10 11:12 UTC by van800

fixes https://github.com/JetBrains/godot-support/issues/71
only for debug tests though, cause for run tests, I don't see good place for that output

2022-01-10 15:18 UTC, ArsenyChernyaev requested changes
Please see comments in FrontendBackendHost.kt

2022-01-10 15:18 UTC, ArseniiCherniaev commented on rider/src/main/kotlin/com/jetbrains/rider/plugins/godot/FrontendBackendHost.kt
> +    private val myDebugProcessProperty: IProperty<DotNetDebugProcess?> = Property(null)
Is it possible to debug several Godot processes simultaneously? If so, then we should also keep track of target process pid (for example), in order to send unit test messages to the correct debug session.

2022-01-10 15:18 UTC, ArsenyChernyaev commented on rider/src/main/kotlin/com/jetbrains/rider/plugins/godot/FrontendBackendHost.kt
>                      debugProcess.initializeDebuggerTask.debuggerInitializingState.advise(lt) {
Could you please subscribe on DotNetDebugProcess.sessionInfo instead? Not-null sessionInfo means that debugger is initialized (and you can get process id from it)

2022-01-10 18:34 UTC, van800 commented on rider/src/main/kotlin/com/jetbrains/rider/plugins/godot/FrontendBackendHost.kt
> +    private val myDebugProcessProperty: IProperty<DotNetDebugProcess?> = Property(null)
Not possible.

2022-01-11 12:41 UTC, ArsenyChernyaev approved these changes

2022-01-11 13:02 UTC, merged